### ISSUE TITLE
Hornet node fails sync after 2 days running fine

### ISSUE THREAD

**Issue by hueznar** [iotaledger/hornet#181]
**Describe the bug**
I'm running a hornet (playbook) node. Actually I have 6 neighbours and at the beginning all is working very fine, but for some reason node begins to lost sync or have problems syncing approx 48 hours after to be started all. I'm running vps for approx 10 days and noted this problem 4 times. Don't matter if I have 6 or 12 or more neighbours, always same problem. When happens this I restart node and download a fresh snapshot and same problem at more or less same time.

**Environment information:**
 - OS: CentOS Linux 8 (Core)
 - RAM: 4 GB
 - Cores: 2 Cores
 - Type: Contabo VPS Server "VPS 300"
 - Browser: Not related
 - HORNET version 0.3.0 (HORC v0.3.8)

**Comment by miili** [comment]
Same here, `database corrupted` after ~48h.

**Comment by muXxer** [comment]
It might be related to the used compression in version 0.3.0.
Should be fixed in the next version.

**Comment by miili** [comment]
Still happens with no compression. Custom profile, no compression, limited to 1gb.
```
Feb 02 10:05:43 qs-dev hornet[17610]: 2020-02-02T10:05:43Z        PANIC        Tangle        HORNET was not shut down correctly. Database is corrupted. Please delete the database folder and start with a new local snapshot.
```

**Comment by muXxer** [comment]
Should be solved with #199
