### ISSUE TITLE
"node not synced" response while the node is synced

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#656]
**Describe the bug**
I often get a "node not synced" response to API called but the node is synced.

**To Reproduce**

I have a Hornet node running (v0.5.2), it reports quite often `node not synced` although the LSMI and the `isSynced`, `isHealthy` fields indicate it is synchronized.
I have tested it with the `getBalances` call but it may occur with other calls, as well:
```
echo $(curl -s -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' '<address>' --data '{"command": "getBalances","addresses":["<my IOTA address>"]}')
echo $(curl -s -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' '<address>' --data '{"command": "getNodeInfo"}' | jq ".isSynced,.isHealthy")
```
```
{"error":"node not synced"}
true true
```
Also if I compare `... --data '{"command": "getNodeInfo"}' | jq -r '.latestSolidSubtangleMilestoneIndex'` with the result from https://nodes.thetangle.org, they do match."
I run the getBalances and getNodeInfo calles with a bash script one after the other with no "sleep" time.

Full response to a "getNodeInfo" command:
```
  "appName": "HORNET",
  "appVersion": "0.5.2",
  "latestMilestone": "TVYNXLYYJCSCBYW9KZGHU9JCXYNOSBBWFKQDLDVHOKVOBSECZGZGZYIAETJNDQHHRQMVNYZSUBZYA9999",
  "latestMilestoneIndex": 1717140,
  "latestSolidSubtangleMilestone": "TVYNXLYYJCSCBYW9KZGHU9JCXYNOSBBWFKQDLDVHOKVOBSECZGZGZYIAETJNDQHHRQMVNYZSUBZYA9999",
  "latestSolidSubtangleMilestoneIndex": 1717140,
  "isSynced": true,
  "isHealthy": true,
  "milestoneStartIndex": 1564509,
  "lastSnapshottedMilestoneIndex": 1717061,
  "neighbors": 7,
  "time": 1599645363000,
  "tips": 95,
  "transactionsToRequest": 0,
  "features": [
    "RemotePOW",
    "WereAddressesSpentFrom"
  ],
  "coordinatorAddress": "UDYXTZBE9GZGPM9SSQV9LTZNDLJIZMPUVVXYXFYVBLIEUHLSEWFTKZZLXYRHHWVQV9MNNX9KZC9D9UZWZ",
  "duration": 0
}
```

**Expected behavior**
I get the balance.

**Environment information:**
 - RAM: 8 GB
 - Cores: 16
 - Type: VM
 - HORNET version: 0.5.2

**Additional context**
This issue has happened a few times before but since the update to 0.5.0 on the 19th August (or the increased rate of milestones per minute) it has become more frequent.

**Comment by ghost** [comment]
My config:
```

{
--
"useProfile": "auto",
"httpAPI": {
"basicAuth": {
"enabled": false,
"username": "",
"passwordHash": "",
"passwordSalt": ""
},
"excludeHealthCheckFromAuth": false,
"permitRemoteAccess": [
"attachToTangle",
"getNodeInfo",
"getBalances",
"checkConsistency",
"getTipInfo",
"getTransactionsToApprove",
"getInclusionStates",
"getNodeAPIConfiguration",
"wereAddressesSpentFrom",
"broadcastTransactions",
"findTransactions",
"storeTransactions",
"getTrytes"
],
"whitelistedAddresses": [],
"bindAddress": "0.0.0.0:11111",
"limits": {
"bodyLengthBytes": 1000000,
"findTransactions": 1000,
"getTrytes": 1000,
"requestsList": 1000
}
},
"tipsel": {
"belowMaxDepth": 15
},
"db": {
"path": "/hornet/mainnetdb",
"debug": false
},
"logger": {
"level": "info",
"disableCaller": true,
"encoding": "console",
"outputPaths": [
"stdout"
]
},
"snapshots": {
"loadType": "local",
"local": {
"intervalSynced": 50,
"intervalUnsynced": 1000,
"path": "snapshots/mainnet/export.bin",
"downloadURLs": [
"https://ls.manapotion.io/export.bin",
"https://x-vps.com/export.bin",
"https://dbfiles.iota.org/mainnet/hornet/latest-export.bin"
]
},
"global": {
"path": "snapshotMainnet.txt",
"spentAddressesPaths": [
"previousEpochsSpentAddresses1.txt",
"previousEpochsSpentAddresses2.txt",
"previousEpochsSpentAddresses3.txt"
],
"index": 1050000
},
"pruning": {
"enabled": true,
"delay": 258000
}
},
"spentAddresses": {
"enabled": true
},
"network": {
"preferIPv6": false,
"gossip": {
"bindAddress": "0.0.0.0:15600",
"reconnectAttemptIntervalSeconds": 60
},
"autopeering": {
"bindAddress": "0.0.0.0:14626",
"runAsEntryNode": false,
"entryNodes": [
"FvfwJuCMoWJvcJLSYww7whPxouZ9WFJ55uyxTxKxJ1ez@enter.hornet.zone:14626",
"EkSLZ4uvSTED1x6KaGzqxoGxjbytt2rPVfbJk1LRLCGL@enter.manapotion.io:18626",
"iotaMk9Rg8wWo1DDeG7fwV9iJ41hvkwFX8w6MyTQgDu@enter.thetangle.org:14627",
"12w9FrzMdDQ42aBgFrv1siHuJMhuZ4SMVHRFSS7Zb72W@entrynode.iotatoken.nl:14626",
"DboTc1v61Xdyvggj8VRszy92ScUTLgfwZaHvXsU8zr7e@entrynode.tanglebay.org:14626",
"31Tz9meznQMm7qSDUgyMmYVeHUCGA7za5Suvbom5hpE9@bender.iota.autopeering.com:14626"
],
"seed": ""
}
},
"node": {
"alias": "",
"showAliasInGetNodeInfo": false,
"disablePlugins": [
"WarpSync",
"Dashboard",
"Graph",
"MQTT",
"Prometheus",
"Spammer",
"ZMQ"
],
"enablePlugins": []
},
"profiling": {
"bindAddress": "localhost:6060"
}
}


```

**Comment by muXxer** [comment]
Hi @g574 and thx for the report.

I see where this problem comes from, because in some API calls, we directly check if latest solid milestone is equal to latest known milestone. This is somewhat on purpose, because you will not get the latest information about the "balances" in that moment, because the state of the latest milestone is not applied yet.

In `getBalances` this may not be a problem, because we also return the `milestoneIndex` of that result, so the client could check if these are the latest balances. But if a client doesn't check this index, and uses the old balances for new transfers, this could go wrong.

Also 2 other calls are affected `wereAddressesSpentFrom` and `getInclusionState`.
IMHO it's better to signal the caller that the node was not completly sync in exactly that moment of the call, instead of replying with outdated information. The caller can just retry the request.
What do you think?

We will also discuss this internally.

**Comment by quietnan** [comment]
IMHO a node that is synced and catches up to each new milestone within few milliseconds should not be considered 'out of sync' for the duration of these few milliseconds. If you decide to promote the current behaviour to a feature, then we'd greatly appreciate a different error message between 'outdated by a millisecond', where it makes sense to repeat the call, and 'significantly outdated' where it does not.

Looking at other blockchains, the consensus behaviour for all other node software seems to be to deliver the most recent known data for e.g. balances. The node already provides sufficient information to the user to determine if the information should be considered current enough or not. I do not think this decision should be enforced on the node level.

**Comment by muXxer** [comment]
I think I will add a small deadline to wait for becoming sync if the node is almost sync when the request arrives.

**Comment by quietnan** [comment]
That would very likely work for us, thanks.

**Comment by muXxer** [comment]
Great, I will implement that tonight.

**Comment by muXxer** [comment]
Fixed in #657

**Comment by ghost** [comment]
Hi @muXxer ,
Unfortunately I still have this issue with 0.5.3-rc3.
I use a script like this:
```
#!/bin/bash

echo $(curl -s --noproxy "*" --connect-timeout 10 --max-time 10 -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' 'http://<address>' --data '{"command": "getBalances","addresses":["<IOTA address>"]}')

echo $(curl -s --noproxy "*" --connect-timeout 10 --max-time 10 -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' 'http://<address>' --data '{"command": "getNodeInfo"}' | jq ".isSynced,.isHealthy")
```

It still reports "node not synced" quite often.

This is the output from `getNodeInfo`:
```
{
  "appName": "HORNET",
  "appVersion": "0.5.3-rc3",
  "latestMilestone": "FNGOUMVLMXRUDAKFZIKBGGSWYQ9TQEDKTS9S9SWHSSKDUFFSXJYAPHIIGXNLXI9MNVMTGWNOEDCE99999",
  "latestMilestoneIndex": 1734991,
  "latestSolidSubtangleMilestone": "FNGOUMVLMXRUDAKFZIKBGGSWYQ9TQEDKTS9S9SWHSSKDUFFSXJYAPHIIGXNLXI9MNVMTGWNOEDCE99999",
  "latestSolidSubtangleMilestoneIndex": 1734991,
  "isSynced": true,
  "isHealthy": true,
  "milestoneStartIndex": 1559930,
  "lastSnapshottedMilestoneIndex": 1734908,
  "neighbors": 7,
  "time": 1599823874000,
  "tips": 101,
  "transactionsToRequest": 0,
  "features": [
    "RemotePOW",
    "WereAddressesSpentFrom"
  ],
  "coordinatorAddress": "UDYXTZBE9GZGPM9SSQV9LTZNDLJIZMPUVVXYXFYVBLIEUHLSEWFTKZZLXYRHHWVQV9MNNX9KZC9D9UZWZ",
  "duration": 0
}
```

**Comment by muXxer** [comment]
can you post the node logs at the same time your script fails?

**Comment by muXxer** [comment]
Closed due to inactivity.
Hit me up if you still have the problem with the next version called chrysalis.  (see develop branch)
